### ISSUE TITLE
Flags defined with underscores are not passed correctly to submodules

### ISSUE THREAD

**Issue by ericksantillanp** [ml-tooling/universal-build#25]
**Describe the bug:**
I have a project with submodules, it could be think as:
```
build.py
|  submodule/
|    |   build.py
```

I defined an argument with using an underscore in the name in both build.py

```{python}
parser.add_argument(
    "--my_token" 
)
```

When the submodule is called from the parent, it is called with an argument `--my-token` which is not detected by the submodule.

**Expected behaviour:**
The names fo the arguments shouldn't be changed between when the parent and the submodule.

**Steps to reproduce the issue:**

**Technical details:**

- Host Machine OS (Windows/Linux/Mac): 
- Browser (Chrome/Firefox/Safari):

**Possible Fix:**
The replacement of `_` to `-` is here: https://github.com/ml-tooling/universal-build/blob/eee9ed5d40c2a9aac4144bad807fde31ab52d8e8/src/universal_build/build_utils.py#L249

**Additional context:**

**Comment by LukasMasuch** [comment]
@ericksantillanp Good catch! The issue is that argparser is automatically converting everything to underscore, so if we want to support parameters with dashes, we need some kind of replacement. But I think we can fix this by replacing the line from above with this workaround:

```python
cli_arg_name = str(arg)
if not any(sys_arg.startswith(f"--{str(cli_arg_name)}") for sys_arg in sys.argv):
    cli_arg_name = cli_arg_name.replace("_", "-")
```

This checks if the underscore notation can be found in the original arguments. If not, it will do the transformation to dashes. We will test this and probably roll out a fix soon :)
